name: dcache_flutter
description: Dcache_flutter is a library for Dio. Dcache_flutter uses sqflite as disk cache and we consider that memery cache is unnecessary. It is used in our product. It is fully tested and stable. Maybe it's useful for you too.
version: 1.1.2
homepage: https://github.com/ligun123/dcache_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  crypto: ^2.1.3
  dio: ^3.0.9
  sqflite: ^1.1.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
